version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siag3_web
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html
    environment:
      # CodeIgniter 4 Environment overrides
      - CI_ENVIRONMENT=development
      # Menghubungkan ke hostname container MySQL yang sudah ada
      - database.default.hostname=photobooth_website_project-mysql-1
      - database.default.database=siag3
      - database.default.username=sail
      - database.default.password=password
      - database.default.DBDriver=MySQLi
      - database.default.port=3306
    networks:
      - existing_sail_network

# Menggunakan Network milik container Sail Anda yang sudah berjalan
networks:
  existing_sail_network:
    external: true
    name: photobooth_website_project_sail # (Ubah menjadi portofolio-new-rihaz_sail jika Anda ingin memakai DB server milik Portofolio)
